-- AlterTable
ALTER TABLE "User"
ADD COLUMN "transactionPin" TEXT,
ADD COLUMN "isPinSet" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "twoFactorSecret" TEXT,
ADD COLUMN "isTwoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "isFrozen" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "dailySwapLimit" DECIMAL(18,2) NOT NULL DEFAULT 1000000,
ADD COLUMN "dailySwapUsed" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN "dailyLimitResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
